# Generated by Django 4.2.6 on 2023-10-23 08:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movie_ninja', '0002_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='access_token_expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='token',
            name='refresh_token_expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
