# Generated by Django 4.2.6 on 2023-10-25 05:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_ninja', '0003_token_access_token_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='image',
            field=models.CharField(max_length=200, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='token',
            name='access_token_expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 25, 5, 35, 49, 148296, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='token',
            name='refresh_token_expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 25, 5, 35, 49, 148296, tzinfo=datetime.timezone.utc)),
        ),
    ]
